# Warnings currently triggered by your code
- ignore: {name: "Avoid lambda"} # 4 hints
- ignore: {name: "Eta reduce"} # 30 hints
- ignore: {name: "Fix pragma markup"} # 36 hints
- ignore: {name: "Functor law"} # 3 hints
- ignore: {name: "Redundant bang pattern"} # 33 hints
- ignore: {name: "Redundant flip"} # 1 hint
- ignore: {name: "Redundant if"} # 1 hint
- ignore: {name: "Use $>"} # 7 hints
- ignore: {name: "Use <$"} # 1 hint
- ignore: {name: "Use <$>"} # 10 hints
- ignore: {name: "Use camelCase"} # 2 hints
- ignore: {name: "Use const"} # 1 hint
- ignore: {name: "Use first"} # 1 hint
- ignore: {name: "Use fold"} # 1 hint
- ignore: {name: "Use gets"} # 9 hints
- ignore: {name: "Use guards"} # 3 hints
- ignore: {name: "Use infix"} # 4 hints
- ignore: {name: "Use map once"} # 1 hint
- ignore: {name: "Use maybe"} # 7 hints
- ignore: {name: "Use second"} # 1 hint
