# Warnings currently triggered by your code
- ignore: {name: "Eta reduce"} # 30 hints
- ignore: {name: "Use <$>"} # 10 hints
# The following are kept for usability and style sake
- ignore: {name: "Avoid lambda"} # 4 hints
- ignore: {name: "Use $>"} # 7 hints
- ignore: {name: "Use <$"} # 1 hint
- ignore: {name: "Use infix"} # 4 hints
