language: c
sudo: false

matrix:
  include:
    - env: SMT="z3" CABAL=1.22 GHC=7.10.1
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1,ocaml,camlidl],sources: [hvr-ghc]}}

# env:
#   - SMT="z3"   GHC="7.10.1" CABAL="1.22"
#   - SMT="cvc4" GHC="7.10.1" CABAL="1.22"

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.cabal
  - $HOME/.ghc

before_install:
 - export PATH="$HOME/.cabal/bin:/opt/ghc/$GHC/bin:/opt/cabal/$CABAL/bin:$PATH"
 - scripts/travis clean_cache "$SMT"

install:
 - scripts/travis install_cabal_deps
 - scripts/travis install_smt "$SMT"

script:
 - scripts/travis do_build && scripts/travis do_test "$SMT"
 - scripts/travis clean_cache "$SMT"

after_failure:
 - scripts/travis dump_fail_logs

notifications:
  slack:
    rooms:
      secure: VT1SqW+4WQKb2PXgObQ/rNdQN8pFK5LaFacxB0fEvRZ2FSbM3qp1NGgii7WHlQdr598+L5qYhkpy1B8ssgNeR7iMmYP4GV/fhCoMd8nTQHLSrTMH8iQgT0D7SnuKdk5FQq1IXWtHjUzXtTIhnkfwOJF/xYf6BMMrO0sCta5JZgg=
    on_success: change
    on_failure: always
    on_start: never
