resolver: lts-12.2

flags:
  liquid-fixpoint:
    devel: true 

packages:
- '.'
extra-deps:
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.2
- located-base-0.1.1.1
- tasty-rerun-1.1.12
- text-format-0.3.2
