
resolver: nightly-2024-04-27

flags:
  liquid-fixpoint:
    devel: true
#   Don't enable z3 linking by default
#   Most of the time, devs don't care about it and it demands the
#   z3 library to be at the linker's reach.
#   link-z3-as-a-library: true

packages:
- '.'

extra-deps:
- rest-rewrite-0.4.2
- smtlib-backends-0.3@rev:2
- smtlib-backends-process-0.3@rev:2
- smtlib-backends-z3-0.3.1
- store-0.7.18
- store-core-0.4.4.6

allow-newer: true
allow-newer-deps:
  - rest-rewrite
  - store-core

nix:
  packages: [z3]
