
resolver: lts-18.27
allow-newer: true

flags:
  liquid-fixpoint:
    devel: true 

packages:
- '.'


extra-deps:
- hashable-1.3.5.0
- git: https://github.com/zgrannan/rest
  commit: 9637b77823ef3ceb909510cad2508e828767f6fb

nix:
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]
