
resolver: nightly-2025-03-20

flags:
  liquid-fixpoint:
    devel: true
#   Don't enable z3 linking by default
#   Most of the time, devs don't care about it and it demands the
#   z3 library to be at the linker's reach.
#   link-z3-as-a-library: true

packages:
- '.'

extra-deps:
- rest-rewrite-0.4.4
- smtlib-backends-0.4
- smtlib-backends-process-0.3@rev:5
- smtlib-backends-z3-0.3.1
  # Needed when overriding the resolver in CI
- tasty-1.5.3

nix:
  packages: [z3, cvc5]
