# GHC 7.10
# resolver: nightly-2015-12-21
# resolver: nightly-2015-09-24

resolver: nightly-2016-01-06

packages:
- .

extra-deps:
- intern-0.9.1.4
- located-base-0.1.0.0
- ascii-progress-0.3.2.0
- concurrent-output-1.7.1
- fgl-visualize-0.1.0.1
- dotgen-0.4.2
